export const ambiences = {
  goetia: {
    dwarven: [
        { x: 15, y: -1, z: -1, night: false },
      { x: 17, y: 2, z: -1, night: false },
      { x: 18, y: 2, z: -1, night: false },
      { x: 18, y: 3, z: -1, night: false },
      { x: 18, y: 4, z: -1, night: false },
      { x: 19, y: 4, z: -1, night: false },
      { x: 17, y: 4, z: -1, night: false },
      { x: 16, y: 4, z: -1, night: false },
    ],
    blacksmith: [
      { x: 14, y: 1, z: -1, night: false },
      { x: 7, y: 0, z: 0, night: false },
    ],
    cave: [
      { x: 6, y: -2, z: -1, night: false },
      { x: 7, y: -2, z: -1, night: false },
      { x: 8, y: -2, z: -1, night: false },
      { x: 16, y: 3, z: -3, night: false },
    ],
    mine: [
      { x: 14, y: 0, z: 0, night: false },
      { x: 14, y: 0, z: -1, night: false },
      { x: 15, y: 0, z: -1, night: false },
      { x: 15, y: 1, z: -1, night: false },
      { x: 16, y: 0, z: -1, night: false },
      { x: 17, y: 0, z: -1, night: false },
      { x: 16, y: 1, z: -1, night: false },
    ],
    cave2: [{ x: 10, y: 1, z: 0, night: false }],
    night: [{ x: 8, y: -1, z: 1, night: false }],
    tavern: [
      { x: 8, y: -1, z: 0, night: false },
      { x: 16, y: 3, z: -1, night: false },
      { x: 16, y: 3, z: -2, night: false },
    ],
    frostfallTown: [
      { x: 7, y: -1, z: 0, night: false },
      { x: 16, y: 2, z: -1, night: false },
    ],
    waterfall: [
      { x: 5, y: -2, z: 0, night: false },
      { x: 5, y: -1, z: 0, night: false },
      { x: 8, y: 0, z: 0, night: false },
    ],
    windForest: [
      { x: 4, y: -1, z: 0, night: false },
      { x: 3, y: -1, z: 0, night: false },
      { x: 3, y: -2, z: 0, night: false },
      { x: 4, y: -2, z: 0, night: false },
      { x: 6, y: -2, z: 0, night: false },
      { x: 9, y: 0, z: 0, night: false },
    ],
    windSnowPeak: [
      { x: 0, y: 0, z: 0, night: false },
      { x: 1, y: 0, z: 0, night: false },
      { x: 2, y: 0, z: 0, night: false },
      { x: 3, y: 0, z: 0, night: false },
      { x: 4, y: 0, z: 0, night: false },
      { x: 9, y: 1, z: 0, night: false },
      { x: 10, y: 0, z: 0, night: false },
      { x: 11, y: 0, z: 0, night: false },
      { x: 13, y: 4, z: 0, night: false },
      { x: 15, y: 4, z: 0, night: false },
    ],
  },
  elysia: {
    forestDay: [
      { x: 0, y: 1, z: 0, night: false },
      { x: -2, y: 0, z: 0, night: false },
      { x: -3, y: 0, z: 0, night: false },
      { x: -3, y: -1, z: 0, night: false },
      { x: -3, y: -2, z: 0, night: false },
      { x: -5, y: -2, z: 0, night: false },
      { x: -5, y: 0, z: 0, night: false },
      { x: -5, y: 1, z: 0, night: false },
      { x: -6, y: -2, z: 0, night: false },
      { x: -6, y: -2, z: 1, night: false },
    ],
    forestDay2: [
      { x: 1, y: 2, z: 0, night: false },
      { x: 0, y: 1, z: 0, night: false },
      { x: 0, y: 2, z: 0, night: false },
      { x: -1, y: 2, z: 0, night: false },
      { x: -1, y: 3, z: 0, night: false },
      { x: -6, y: 0, z: 0, night: false },
    ],
    forestNight: [
      { x: 0, y: 1, z: 0, night: true },
      { x: -2, y: 0, z: 0, night: true },
      { x: -3, y: 0, z: 0, night: true },
      { x: -3, y: -1, z: 0, night: true },
      { x: -3, y: -2, z: 0, night: true },
      { x: -5, y: -2, z: 0, night: true },
      { x: -5, y: 0, z: 0, night: true },
      { x: -5, y: 1, z: 0, night: true },
      { x: -6, y: -2, z: 0, night: true },
      { x: -6, y: -2, z: 1, night: true },
      { x: 1, y: 2, z: 0, night: true },
      { x: 0, y: 1, z: 0, night: true },
      { x: 0, y: 2, z: 0, night: true },
      { x: -1, y: 2, z: 0, night: true },
      { x: -1, y: 3, z: 0, night: true },
      { x: -6, y: 0, z: 0, night: true },
      { x: 0, y: -2, z: 0, night: true },
      { x: -1, y: -2, z: 0, night: true },
      { x: -1, y: -1, z: 0, night: true },
      { x: -1, y: 0, z: 0, night: true },
      { x: -2, y: -2, z: 0, night: true },
    ],
    water: [
      { x: 0, y: 0, z: 0, night: false },
      { x: 0, y: -1, z: 0, night: false },
      { x: -1, y: 2, z: 0, night: false },
      { x: -1, y: 1, z: 0, night: false },
      { x: -4, y: -2, z: 0, night: false },
      { x: -4, y: -1, z: 0, night: false },
      { x: -4, y: 0, z: 0, night: false },
      { x: -4, y: 1, z: 0, night: false },
      { x: -4, y: 2, z: 0, night: false },
      { x: -5, y: -1, z: 0, night: false },
    ],
    grasslands: [
      { x: 0, y: -2, z: 0, night: false },
      { x: -1, y: -2, z: 0, night: false },
      { x: -1, y: -1, z: 0, night: false },
      { x: -1, y: 0, z: 0, night: false },
      { x: -2, y: -2, z: 0, night: false },
    ],
    cave: [
      { x: 5, y: 0, z: 0, night: false },
      { x: 1, y: 0, z: 0, night: false },
      { x: 2, y: 0, z: 0, night: false },
      { x: 3, y: 0, z: 0, night: false },
      { x: 4, y: 0, z: 0, night: false },
      { x: -1, y: 1, z: -1, night: false },
      { x: -1, y: 0, z: -1, night: false },
      { x: -2, y: 0, z: -1, night: false },
      { x: -3, y: 0, z: -1, night: false },
      { x: -3, y: -1, z: -1, night: false },
      { x: -4, y: -1, z: -1, night: false },
      { x: -5, y: -1, z: -1, night: false },
      { x: -5, y: -2, z: -1, night: false },
      { x: -1, y: 4, z: 0, night: false },
      { x: -2, y: 4, z: 0, night: false },
      { x: -3, y: 4, z: 0, night: false },
      { x: -3, y: 3, z: 0, night: false },
      { x: -4, y: 3, z: 0, night: false },
      { x: 3, y: 2, z: 0, night: false },
      { x: 3, y: 1, z: 0, night: false },
      { x: 3, y: 3, z: 0, night: false },
      { x: 4, y: 3, z: 0, night: false },
      { x: 4, y: 4, z: 0, night: false },
      { x: 4, y: 5, z: 0, night: false },
    ],
  }
};
