export const tracklist = {
    goetia: {
      musicGate: [{ x: 8, y: 0, z: 0, night: false }],
      musicMountainsNjol: [
      { x: 3, y: -1, z: 0, night: false },
      { x: 3, y: -2, z: 0, night: false },
      { x: 5, y: -1, z: 0, night: false },
      { x: 9, y: 0, z: 0, night: false },
      { x: 10, y: 0, z: 0, night: false },
      { x: 11, y: 0, z: 0, night: false },
    ],
    musicFlute: [
      {x: 4, y: -1, z: 0, night: false},
      {x: 4, y: -2, z: 0, night: false},
    ],
    musicRoyalty: [
      { x: 7, y: -2, z: 0, night: false },
      { x: 12, y: 0, z: 0, night: false },
      { x: 13, y: 0, z: 0, night: false },
      { x: 17, y: 0, z: -1, night: false },
      { x: 18, y: 0, z: -1, night: false },
    ],
    musicTown: [{ x: 7, y: -1, z: 0, night: false }],
    musicBattleAmbush: [{ x: 5, y: -1, z: 0, night: false }],
    musicBattleCalm: [
      { x: 5, y: -2, z: 0, night: false },
      { x: 6, y: -2, z: 0, night: false },
    ],
    musicBattleBig: [{ x: 9, y: -2, z: -1, night: false }],
    musicMountainsCalm: [
      { x: 2, y: 0, z: 0, night: false },
      { x: 16, y: 4, z: -1, night: false },
    ],
    musicGoetia: [{ x: 13, y: 0, z: 0, night: false }],
    musicDwarvenCity: [{ x: 15, y: 0, z: -1, night: false }],
    musicFrostfall: [{ x: 6, y: -1, z: 0, night: false }],
    musicBattleSmall: [{ x: 9, y: 1, z: 0, night: false }],
    musicBattleWolf: [{ x: 10, y: 1, z: 0, night: false }],
    musicBattleDragon: [{ x: 14, y: 4, z: 0, night: false }],
    musicMystical: [
      { x: 17, y: 2, z: -1, night: false },
      { x: 18, y: 2, z: -1, night: false },
      { x: 18, y: 3, z: -1, night: false },
      { x: 18, y: 4, z: -1, night: false },
    ],
  },
  elysia: {
    musicBattle1: [
      { x: 3, y: 1, z: 0, night: false },
      { x: 3, y: 3, z: 0, night: false },
    ],
    musicBattle2: [
      { x: 0, y: 0, z: 0, night: false },
      { x: 1, y: 0, z: 0, night: false },
      { x: -2, y: 4, z: 0, night: false },
      { x: -3, y: 4, z: 0, night: false },
      { x: -3, y: 3, z: 0, night: false },
      { x: -2, y: 4, z: 0, night: true },
      { x: -3, y: 4, z: 0, night: true },
      { x: -3, y: 3, z: 0, night: true },
    ],
    musicMoritio: [
      { x: -5, y: 0, z: 0, night: false },
      { x: -5, y: 0, z: 0, night: true },
      { x: -1, y: 2, z: 0, night: false },
      { x: -1, y: 2, z: 0, night: true },
    ],
    musicBossBattle2: [
      { x: 4, y: 5, z: 0, night: false },
      { x: -3, y: -1, z: 0, night: false },
      { x: -3, y: -1, z: 0, night: true },
    ],
    musicChapel: [
      { x: -6, y: 0, z: 0, night: false},
      { x: -6, y: 0, z: 0, night: true },
    ],
    musicLore1: [
      { x: -1, y: 0, z: 0, night: false },
      { x: -1, y: 0, z: 0, night: true },
      { x: 0, y: 2, z: 0, night: false },
      { x: 0, y: 2, z: 0, night: true },
      { x: 1, y: 2, z: 0, night: false },
      { x: 1, y: 2, z: 0, night: true },
    ],
    musicCave1: [
      { x: 2, y: 2, z: 0, night: false },
      { x: 2, y: 2, z: 0, night: true },
      { x: 3, y: 2, z: 0, night: false },
    ],
    musicSerpents: [
      { x: -5, y: -2, z: -1, night: false },
    ],
    musicBlacksmith: [
      { x: -5, y: -1, z: 0, night: false },
      { x: -5, y: -1, z: 0, night: true },
    ],
    musicBattle3: [
      { x: -6, y: 0, z: 0, night: false },
      { x: -6, y: 0, z: 0, night: true },
      { x: -1, y: 0, z: 0, night: false },
      { x: -1, y: 0, z: 0, night: true },
      { x: 0, y: 2, z: 0, night: false },
      { x: 0, y: 2, z: 0, night: true },
      { x: 1, y: 2, z: 0, night: false},
      { x: 1, y: 2, z: 0, night: true },
      { x: -5, y: -1, z: 0, night: false },
      { x: -5, y: -1, z: 0, night: true },
      { x: 2, y: 2, z: 0, night: false },
      { x: 2, y: 2, z: 0, night: true },
      { x: 3, y: 2, z: 0, night: false },
      { x: 4, y: 3, z: 0, night: false },
      { x: 4, y: 4, z: 0, night: false },
    ],
    musicCave2: [
      { x: -1, y: 1, z: -1, night: false },
      { x: -1, y: 0, z: -1, night: false },
      { x: -2, y: 0, z: -1, night: false },
      { x: -3, y: 0, z: -1, night: false },
      { x: -3, y: -1, z: -1, night: false },
      { x: -4, y: -1, z: -1, night: false },
      { x: -5, y: -1, z: -1, night: false },
      { x: -5, y: -2, z: -1, night: false },
    ],
    musicBattle4: [
      { x: -1, y: 1, z: -1, night: false },
      { x: -1, y: 0, z: -1, night: false },
      { x: -2, y: 0, z: -1, night: false },
      { x: -3, y: 0, z: -1, night: false },
      { x: -3, y: -1, z: -1, night: false },
      { x: -4, y: -1, z: -1, night: false },
      { x: -5, y: -1, z: -1, night: false },
    ],
    musicTavern2: [
      { x: -6, y: -2, z: 0, night: false },
      { x: -6, y: -2, z: 0, night: true },
      { x: -6, y: -2, z: 1, night: false },
      { x: -6, y: -2, z: 1, night: true },
    ],
    musicRiverwood: [
      { x: -5, y: -2, z: 0, night: false },
      { x: -5, y: -2, z: 0, night: true },
    ],
    musicMysterywoods: [
      { x: -4, y: -2, z: 0, night: false },
      { x: -4, y: -2, z: 0, night: true },
      { x: -4, y: -1, z: 0, night: false },
      { x: -4, y: -1, z: 0, night: true },
      { x: -4, y: 0, z: 0, night: false },
      { x: -4, y: 0, z: 0, night: true },
    ],
    musicKing: [
      { x: -5, y: 1, z: 0, night: false },
      { x: -5, y: 1, z: 0, night: true },
    ],
    musicMystery: [
      { x: -3, y: 0, z: 0, night: false },
      { x: -3, y: 0, z: 0, night: true },
      { x: -2, y: 0, z: 0, night: false },
      { x: -2, y: 0, z: 0, night: true },
      { x: -3, y: -2, z: 0, night: false },
      { x: -3, y: -2, z: 0, night: true },
    ],
    musicMysterywoods2: [
      { x: 0, y: 0, z: 0, night: false },
      { x: 0, y: 0, z: 0, night: true },
      { x: 0, y: -1, z: 0, night: false },
      { x: 0, y: -1, z: 0, night: true },
      { x: 0, y: -2, z: 0, night: false },
      { x: 0, y: -2, z: 0, night: true },
      { x: 0, y: 1, z: 0, night: false },
      { x: 0, y: 1, z: 0, night: true },
    ],
    musicStart: [
      { x: -1, y: 3, z: 0, night: false },
      { x: -1, y: 3, z: 0, night: true },
    ],
    musicCave5: [
      { x: 3, y: 1, z: 0, night: false },
      { x: 3, y: 3, z: 0, night: false },
    ],
    musicCatacombs: [
      { x: 4, y: 3, z: 0, night: false },
      { x: 4, y: 4, z: 0, night: false },
    ],
  }
};
