export const tracklist = {
  musicGate: [{ x: 8, y: 0, z: 0 }],
  musicMountainsNjol: [
    { x: 3, y: -1, z: 0 },
    { x: 3, y: -2, z: 0 },
    { x: 5, y: -1, z: 0 },
    { x: 9, y: 0, z: 0 },
    { x: 10, y: 0, z: 0 },
    { x: 11, y: 0, z: 0 },
  ],
  musicFlute: [
    {x: 4, y: -1, z: 0},
    {x: 4, y: -2, z: 0},
  ],
  musicRoyalty: [
    { x: 7, y: -2, z: 0 },
    { x: 12, y: 0, z: 0 },
    { x: 13, y: 0, z: 0 },
    { x: 17, y: 0, z: -1 },
    { x: 18, y: 0, z: -1 },
  ],
  musicTown: [{ x: 7, y: -1, z: 0 }],
  musicBattleAmbush: [{ x: 5, y: -1, z: 0 }],
  musicBattleCalm: [
    { x: 5, y: -2, z: 0 },
    { x: 6, y: -2, z: 0 },
  ],
  musicBattleBig: [{ x: 9, y: -2, z: -1 }],
  musicMountainsCalm: [
    { x: 2, y: 0, z: 0 },
    { x: 16, y: 4, z: -1 },
  ],
  musicGoetia: [{ x: 13, y: 0, z: 0 }],
  musicDwarvenCity: [{ x: 15, y: 0, z: -1 }],
  musicFrostfall: [{ x: 6, y: -1, z: 0 }],
  musicBattleSmall: [{ x: 9, y: 1, z: 0 }],
  musicBattleWolf: [{ x: 10, y: 1, z: 0 }],
  musicBattleDragon: [{ x: 14, y: 4, z: 0 }],
  musicMystical: [
    { x: 17, y: 2, z: -1 },
    { x: 18, y: 2, z: -1 },
    { x: 18, y: 3, z: -1 },
    { x: 18, y: 4, z: -1 },
  ],
};
